### ISSUE TITLE
pex doesn't seem to work inside a python3.4 venv

### ISSUE THREAD

**Issue by wickman** [twitter/commons#283]
It works in python3.4 virtualenv but not in python3.4 stdlib venv:

``` shell
mba=dist=; python3.4 -m venv pex34
mba=dist=; source pex34/bin/activate
(pex34) mba=dist=; pip install twitter.common.python-0.5.0.tar.gz
Unpacking ./twitter.common.python-0.5.0.tar.gz
  Running setup.py (path:/var/folders/4d/9tz0cd5n2n7947xs21gspsxc0000gp/T/pip-87yp7_4h-build/setup.py) egg_info for package from file:///Users/wickman/clients/commons/dist/twitter.common.python-0.5.0.tar.gz

Downloading/unpacking wheel (from twitter.common.python==0.5.0)
  Downloading wheel-0.23.0-py2.py3-none-any.whl (61kB): 61kB downloaded
Requirement already satisfied (use --upgrade to upgrade): setuptools>=1 in ./pex34/lib/python3.4/site-packages (from twitter.common.python==0.5.0)
Installing collected packages: wheel, twitter.common.python
  Running setup.py install for twitter.common.python
    Skipping installation of /Users/wickman/clients/commons/dist/pex34/lib/python3.4/site-packages/twitter/__init__.py (namespace package)
    Skipping installation of /Users/wickman/clients/commons/dist/pex34/lib/python3.4/site-packages/twitter/common/__init__.py (namespace package)

    Installing /Users/wickman/clients/commons/dist/pex34/lib/python3.4/site-packages/twitter.common.python-0.5.0-py3.4-nspkg.pth
    Installing pex script to /Users/wickman/clients/commons/dist/pex34/bin
Successfully installed wheel twitter.common.python
Cleaning up...
(pex34) mba=dist=; pex --repo=. -r twitter.common.python==0.5.0 -o pex34.pex -e twitter.common.python.bin.pex:main
**** Failed to install twitter.common.python-0.5.0. stdout:

**** Failed to install twitter.common.python-0.5.0. stderr:
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/Users/wickman/clients/commons/dist/pex34/lib/python3.4/site-packages/setuptools/__init__.py", line 11, in <module>
    from setuptools.extension import Extension
  File "/Users/wickman/clients/commons/dist/pex34/lib/python3.4/site-packages/setuptools/extension.py", line 5, in <module>
    from setuptools.dist import _get_unpatched
  File "/Users/wickman/clients/commons/dist/pex34/lib/python3.4/site-packages/setuptools/dist.py", line 16, in <module>
    import pkg_resources
  File "/Users/wickman/clients/commons/dist/pex34/lib/python3.4/site-packages/pkg_resources.py", line 2717, in <module>
    add_activation_listener(lambda dist: dist.activate())
  File "/Users/wickman/clients/commons/dist/pex34/lib/python3.4/site-packages/pkg_resources.py", line 682, in subscribe
    callback(dist)
  File "/Users/wickman/clients/commons/dist/pex34/lib/python3.4/site-packages/pkg_resources.py", line 2717, in <lambda>
    add_activation_listener(lambda dist: dist.activate())
  File "/Users/wickman/clients/commons/dist/pex34/lib/python3.4/site-packages/pkg_resources.py", line 2255, in activate
    list(map(declare_namespace, self._get_metadata('namespace_packages.txt')))
  File "/Users/wickman/clients/commons/dist/pex34/lib/python3.4/site-packages/pkg_resources.py", line 1851, in declare_namespace
    path = sys.modules[parent].__path__
KeyError: 'twitter'

Traceback (most recent call last):
  File "/Users/wickman/clients/commons/dist/pex34/bin/pex", line 9, in <module>
    load_entry_point('twitter.common.python==0.5.0', 'console_scripts', 'pex')()
  File "/Users/wickman/clients/commons/dist/pex34/lib/python3.4/site-packages/twitter/common/python/bin/pex.py", line 309, in main
    pex_builder = build_pex(args, options)
  File "/Users/wickman/clients/commons/dist/pex34/lib/python3.4/site-packages/twitter/common/python/bin/pex.py", line 273, in build_pex
    platform=options.platform)
  File "/Users/wickman/clients/commons/dist/pex34/lib/python3.4/site-packages/twitter/common/python/resolver.py", line 107, in resolve
    new_requirements.update(requires(highest_package, requirement))
  File "/Users/wickman/clients/commons/dist/pex34/lib/python3.4/site-packages/twitter/common/python/resolver.py", line 81, in requires
    raise Untranslateable('Package %s is not translateable.' % package)
twitter.common.python.resolver.Untranslateable: Package SourcePackage('./twitter.common.python-0.5.0.tar.gz') is not translateable.
(pex34) mba=dist=; deactivate
```

But when using python3.4 with third party virtualenv:

``` shell
mba=dist=; python3.4 -m virtualenv pex34legacy
Using base prefix '/Users/wickman/Python/CPython-3.4.0'
New python executable in pex34legacy/bin/python3.4
Also creating executable in pex34legacy/bin/python
Installing setuptools, pip...done.
mba=dist=; source pex34legacy/bin/activate
(pex34legacy)mba=dist=; pip install twitter.common.python-0.5.0.tar.gz 
Unpacking ./twitter.common.python-0.5.0.tar.gz
  Running setup.py (path:/var/folders/4d/9tz0cd5n2n7947xs21gspsxc0000gp/T/pip-8f3py8_s-build/setup.py) egg_info for package from file:///Users/wickman/clients/commons/dist/twitter.common.python-0.5.0.tar.gz

Downloading/unpacking wheel (from twitter.common.python==0.5.0)
  Downloading wheel-0.23.0-py2.py3-none-any.whl (61kB): 61kB downloaded
Requirement already satisfied (use --upgrade to upgrade): setuptools>=1 in ./pex34legacy/lib/python3.4/site-packages (from twitter.common.python==0.5.0)
Installing collected packages: wheel, twitter.common.python
  Running setup.py install for twitter.common.python
    Skipping installation of /Users/wickman/clients/commons/dist/pex34legacy/lib/python3.4/site-packages/twitter/__init__.py (namespace package)
    Skipping installation of /Users/wickman/clients/commons/dist/pex34legacy/lib/python3.4/site-packages/twitter/common/__init__.py (namespace package)

    Installing /Users/wickman/clients/commons/dist/pex34legacy/lib/python3.4/site-packages/twitter.common.python-0.5.0-py3.4-nspkg.pth
    Installing pex script to /Users/wickman/clients/commons/dist/pex34legacy/bin
Successfully installed wheel twitter.common.python
Cleaning up...
(pex34legacy)mba=dist=; pex --repo=. -r twitter.common.python==0.5.0 -o pex34legacy.pex -e twitter.common.python.bin.pex:main
(pex34legacy)mba=dist=; ./pex34legacy.pex --help
Usage: pex34legacy.pex [options]

pex34legacy.pex builds a PEX (Python Executable) file based on the given specifications: sources, requirements, their dependencies and other options

Options:
  --version             show program's version number and exit
  -h, --help            show this help message and exit
  --pypi, --no-pypi     Whether to use pypi to resolve dependencies; Default:
                        use pypi
  --wheel, --no-wheel   Whether to allow wheel distributions; Default: allow
                        wheels
  --build, --no-build   Whether to allow building of distributions from
                        source; Default: allow builds
  --python=PYTHON       The Python interpreter to use to build the pex.
                        Either specify an explicit path to an interpreter, or
                        specify a binary accessible on $PATH. Default: Use
                        current interpreter.
  --platform=PLATFORM   The platform for which to build the PEX.  Default:
                        %macosx-10.7-x86_64
  --zip-safe, --not-zip-safe
                        Whether or not the sources in the pex file are zip
                        safe.  If they are not zip safe, they will be written
                        to disk prior to execution; Default: zip safe.
  --always-write-cache  Always write the internally cached distributions to
                        disk prior to invoking the pex source code.  This can
                        use less memory in RAM constrained environments.
                        [Default: False]
  --ignore-errors       Ignore run-time requirement resolution errors when
                        invoking the pex. [Default: False]
  --inherit-path        Inherit the contents of sys.path (including site-
                        packages) running the pex. [Default: False]
  --cache-dir=CACHE_DIR
                        The local cache directory to use for speeding up
                        requirement lookups; [Default:
                        /Users/wickman/.pex/build]
  -o PEX_NAME, -p PEX_NAME, --output-file=PEX_NAME, --pex-name=PEX_NAME
                        The name of the generated .pex file: Omiting this will
                        run PEX immediately and not save it to a file.
  -e ENTRY_POINT, --entry-point=ENTRY_POINT
                        The entry point for this pex; Omiting this will enter
                        the python REPL with sources and requirements
                        available for import.  Can be either a module or
                        EntryPoint (module:function) format.
  -r REQUIREMENT, --requirement=REQUIREMENT
                        requirement to be included; may be specified multiple
                        times.
  --repo=PATH           Additional repository path (directory or URL) to look
                        for requirements.
  -s DIR, --source-dir=DIR
                        Source to be packaged; This <DIR> should be a pip-
                        installable project with a setup.py.
  -v, --verbosity       Turn on logging verbosity.
```

**Comment by bhuvaneswaran** [comment]
it doesn't seem to work in py2.7 either. we couldn't run pex inside py27 venv.

we face this issue when using aurora (pex) inside venv. The .aurora use custom libs installed inside same venv.
