### ISSUE TITLE
Error from Junit Runner

### ISSUE THREAD

**Issue by ericzundel** [twitter/commons#359]
See https://github.com/pantsbuild/pants/issues/1234 for some details.

I'm getting this stacktrace when running a test in pants that uses the twitter junit runner:

```
./pants test foo:test --no-test-junit-suppress-output
                   .E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E
                     Time: 462.17
                     There were 185 failures:
                     1) Test mechanism
                     java.lang.NullPointerException
                     	at com.twitter.common.junit.runner.ConsoleRunner$StreamCapturingListener.testStarted(ConsoleRunner.java:205)
                     	at com.twitter.common.junit.runner.ForwardingListener$3.fire(ForwardingListener.java:60)
                     	at com.twitter.common.junit.runner.ForwardingListener.fire(ForwardingListener.java:34)
                     	at com.twitter.common.junit.runner.ForwardingListener.testStarted(ForwardingListener.java:58)
                     	at com.twitter.common.junit.runner.AbortableListener.testStarted(AbortableListener.java:29)
                     	at org.junit.runner.notification.SynchronizedRunListener.testStarted(SynchronizedRunListener.java:49)
                     	at org.junit.runner.notification.RunNotifier$3.notifyListener(RunNotifier.java:121)
                     	at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
                     	at org.junit.runner.notification.RunNotifier.fireTestStarted(RunNotifier.java:118)
                     	at org.junit.internal.runners.ErrorReportingRunner.runCause(ErrorReportingRunner.java:64)
                     	at org.junit.internal.runners.ErrorReportingRunner.run(ErrorReportingRunner.java:38)
                     	at com.twitter.common.junit.runner.CompositeRequest.runChild(CompositeRequest.java:63)
                     	at com.twitter.common.junit.runner.ConcurrentCompositeRequest$1$1.run(ConcurrentCompositeRequest.java:33)
                     	at com.twitter.common.junit.runner.ConcurrentRunnerScheduler.finished(ConcurrentRunnerScheduler.java:82)
                     	at com.twitter.common.junit.runner.ConcurrentCompositeRequest$1.evaluate(ConcurrentCompositeRequest.java:42)
                     	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
                     	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
                     	at com.twitter.common.junit.runner.ConsoleRunner.run(ConsoleRunner.java:323)
                     	at com.twitter.common.junit.runner.ConsoleRunner.main(ConsoleRunner.java:635)
```

The code in question is:
```
203:    @Override
204:    public void testStarted(Description description) throws Exception {
205:      captures.get(description.getTestClass()).open();
206:      super.testStarted(description);
207:    }
```

This code hasn't been updated in twitter commons since last May and I was hoping that maybe this has been encountered at Twitter and a fix not yet pushed to the open source version.  If not, let me know and I'll dig into it more.

**Comment by jsirois** [comment]
What junit jar is pants using in your repo?  You can check the cmdline in the pants server console to find out most easily / surely.  When I look at 4.11, which the pants repo itself uses, the line numbers for ErrorReportingRunner for example don't match up: https://github.com/junit-team/junit/blob/r4.11/src/main/java/org/junit/internal/runners/ErrorReportingRunner.java

**Comment by ericzundel** [comment]
I have updated to JUnit 4.12.  I will try backing it down and see if I can reproduce the error.  The maven builder has been using 4.12 for a while and I was just keeping the pants and maven build in sync.

**Comment by areitz** [comment]
Hi John,

I'm probably missing something, but it looks like pantsbuild/pants is using junit 4.10:

https://github.com/pantsbuild/pants/blob/master/BUILD.tools#L126

When I test the `usethrift` example on master, this is what I see pants invoking to run tests:

```
/usr/bin/java -Djava.awt.headless=true -Xmx1g -XX:MaxPermSize=256m -XX:-UseSplitVerifier -cp .pants.d/ivy/jars/junit/junit-dep/jars/junit-dep-4.10.jar:.pants.d/ivy/jars/org.hamcrest/hamcrest-core/jars/hamcrest-core-1.2.jar:.pants.d/ivy/jars/com.twitter.common/junit-runner/jars/junit-runner-0.0.41.jar:.pants.d/ivy/jars/com.twitter.common/junit-runner-annotations/jars/junit-runner-annotations-0.0.6.jar:.pants.d/ivy/jars/com.twitter.common/junit-runner-withretry/jars/junit-runner-withretry-0.0.3.jar:.pants.d/ivy/jars/args4j/args4j/jars/args4j-2.0.16.jar:.pants.d/ivy/jars/com.google.guava/guava/bundles/guava-16.0.jar:.pants.d/ivy/jars/com.google.code.findbugs/jsr305/jars/jsr305-2.0.1.jar:.pants.d/compile/jvm/java/classes:.pants.d/compile/jvm/java/apt-processor-info-global:.pants.d/ivy/jars/junit/junit/jars/junit-4.11.jar:.pants.d/ivy/jars/org.hamcrest/hamcrest-core/jars/hamcrest-core-1.3.jar:.pants.d/ivy/jars/commons-lang/commons-lang/jars/commons-lang-2.5.jar:.pants.d/ivy/jars/org.apache.thrift/libthrift/jars/libthrift-0.5.0-1.jar:.pants.d/ivy/jars/org.slf4j/slf4j-api/jars/slf4j-api-1.6.1.jar com.twitter.common.junit.runner.ConsoleRunner -suppress-output -outdir /Users/areitz/workspace/pants/.pants.d/test/junit -parallel-threads 0 com.pants.examples.usethrift.UseThriftTest
```

Assuming I'm looking at the right file, Twitter is using the same version of junit internally (4.10), but 0.0.42 of junit-runner.

**Comment by jsirois** [comment]
Tool uses 4.10, tests use 4.11 (3rdparty/BUILD) - but this is besides the real point which is not enough data.  I only mentioned the pants repo version since it was the only one handy.  Eric's version is the one that counts.

**Comment by areitz** [comment]
Agree that Eric's version is the one that counts. I mention the version Twitter is using because if this is an issue due to running 4.12, it's probably not something that Twitter has seen.

**Comment by ericzundel** [comment]
I appreciate the offers of help. I plan to dig on this myself, i just
wanted to know if there were unpublished updates to the Twitter commons
ConsoleRunner or other folks with the same issue.
