### ISSUE TITLE
pants.bootstrap paniced

### ISSUE THREAD

**Issue by ddwolf** [twitter/commons#458]
### my system is ubuntu14.04, when I issued pants.bootstrap, I got errors as below:

% `/usr/local/src/twitter-commons$ ./pants.bootstrap`

Using /usr/bin/python
Installing virtualenv
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1294k  100 1294k    0     0  4772k      0 --:--:-- --:--:-- --:--:-- 4758k
Running virtualenv with interpreter /usr/bin/python
New python executable in ./build-support/python/../../.python/bootstrap/bin/python
Installing Setuptools.......................................................................................done.
Installing Pip.......................................................................................................done.
Script ./build-support/python/../../.python/bootstrap/bin/activate.csh cannot be made relative (it's not a normal script that starts with #!/usr/local/src/twitter-commons/.python/bootstrap/bin/python)
Making script ./build-support/python/../../.python/bootstrap/bin/pip relative
Making script ./build-support/python/../../.python/bootstrap/bin/pip-2.7 relative
Making script ./build-support/python/../../.python/bootstrap/bin/easy_install relative
Making script ./build-support/python/../../.python/bootstrap/bin/easy_install-2.7 relative
Script ./build-support/python/../../.python/bootstrap/bin/activate.fish cannot be made relative (it's not a normal script that starts with #!/usr/local/src/twitter-commons/.python/bootstrap/bin/python)
Downloading/unpacking pystache==0.5.3
  Downloading pystache-0.5.3.tar.gz (74kB): 74kB downloaded
  Storing download in cache at ./.pants.d/.pip.cache/https%3A%2F%2Fpypi.python.org%2Fpackages%2F08%2Fe6%2Fc0345da4dbccdcd4d4054e77ba3b9064d05064564d4b9d5978d07b2aab7d%2Fpystache-0.5.3.tar.gz
  Running setup.py egg_info for package pystache
    pystache: using: version '0.9.8' of <module 'setuptools' from '/usr/local/src/twitter-commons/.python/bootstrap/local/lib/python2.7/site-packages/setuptools/__init__.pyc'>

Installing collected packages: pystache
  Running setup.py install for pystache
    pystache: using: version '0.9.8' of <module 'setuptools' from '/usr/local/src/twitter-commons/.python/bootstrap/local/lib/python2.7/site-packages/setuptools/__init__.pyc'>

    Installing pystache script to /usr/local/src/twitter-commons/.python/bootstrap/bin
    Installing pystache-test script to /usr/local/src/twitter-commons/.python/bootstrap/bin
Successfully installed pystache
Cleaning up...
Downloading/unpacking python-daemon==1.5.5
  Downloading python-daemon-1.5.5.tar.gz (41kB): 41kB downloaded
  Storing download in cache at ./.pants.d/.pip.cache/https%3A%2F%2Fpypi.python.org%2Fpackages%2Fee%2Fe2%2F4f186dd429c12dfd7d0f62c3ca04416e146cc6a700310e09d95c3da85e32%2Fpython-daemon-1.5.5.tar.gz
  Running setup.py egg_info for package python-daemon

    warning: no files found matching 'TODO'
Downloading/unpacking setuptools from https://pypi.python.org/packages/41/5f/6da80400340fd48ba4ae1c673be4dc3821ac06cd9821ea60f9c7d32a009f/setuptools-38.4.0.zip#md5=3426bbf31662b4067dc79edc0fa21a2e (from python-daemon==1.5.5)
  Downloading setuptools-38.4.0.zip (737kB): 737kB downloaded
  Storing download in cache at ./.pants.d/.pip.cache/https%3A%2F%2Fpypi.python.org%2Fpackages%2F41%2F5f%2F6da80400340fd48ba4ae1c673be4dc3821ac06cd9821ea60f9c7d32a009f%2Fsetuptools-38.4.0.zip
  Running setup.py egg_info for package setuptools
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    warning: no files found matching '*' under directory 'setuptools/_vendor'
Downloading/unpacking lockfile>=0.7 (from python-daemon==1.5.5)
  Downloading lockfile-0.12.2.tar.gz
  Storing download in cache at ./.pants.d/.pip.cache/https%3A%2F%2Fpypi.python.org%2Fpackages%2F17%2F47%2F72cb04a58a35ec495f96984dddb48232b551aafb95bde614605b754fe6f7%2Flockfile-0.12.2.tar.gz
  Running setup.py egg_info for package lockfile
    Download error on https://pypi.python.org/simple/pbr/: [Errno 104] Connection reset by peer -- Some packages may not be found!
    Couldn't find index page for 'pbr' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [Errno 104] Connection reset by peer -- Some packages may not be found!
    No local packages or download links found for pbr>=1.8
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/usr/local/src/twitter-commons/.python/bootstrap/build/lockfile/setup.py", line 29, in <module>
        pbr=True)
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/src/twitter-commons/.python/bootstrap/local/lib/python2.7/site-packages/setuptools/dist.py", line 265, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/usr/local/src/twitter-commons/.python/bootstrap/local/lib/python2.7/site-packages/setuptools/dist.py", line 289, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/usr/local/src/twitter-commons/.python/bootstrap/local/lib/python2.7/site-packages/pkg_resources.py", line 618, in resolve
        dist = best[req.key] = env.best_match(req, self, installer)
      File "/usr/local/src/twitter-commons/.python/bootstrap/local/lib/python2.7/site-packages/pkg_resources.py", line 862, in best_match
        return self.obtain(req, installer) # try and download/install
      File "/usr/local/src/twitter-commons/.python/bootstrap/local/lib/python2.7/site-packages/pkg_resources.py", line 874, in obtain
        return installer(requirement)
      File "/usr/local/src/twitter-commons/.python/bootstrap/local/lib/python2.7/site-packages/setuptools/dist.py", line 339, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/local/src/twitter-commons/.python/bootstrap/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 617, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pbr>=1.8')
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/pbr/: [Errno 104] Connection reset by peer -- Some packages may not be found!

Couldn't find index page for 'pbr' (maybe misspelled?)

Download error on https://pypi.python.org/simple/: [Errno 104] Connection reset by peer -- Some packages may not be found!

No local packages or download links found for pbr>=1.8

Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/usr/local/src/twitter-commons/.python/bootstrap/build/lockfile/setup.py", line 29, in <module>

    pbr=True)

  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/local/src/twitter-commons/.python/bootstrap/local/lib/python2.7/site-packages/setuptools/dist.py", line 265, in __init__

    self.fetch_build_eggs(attrs.pop('setup_requires'))

  File "/usr/local/src/twitter-commons/.python/bootstrap/local/lib/python2.7/site-packages/setuptools/dist.py", line 289, in fetch_build_eggs

    parse_requirements(requires), installer=self.fetch_build_egg

  File "/usr/local/src/twitter-commons/.python/bootstrap/local/lib/python2.7/site-packages/pkg_resources.py", line 618, in resolve

    dist = best[req.key] = env.best_match(req, self, installer)

  File "/usr/local/src/twitter-commons/.python/bootstrap/local/lib/python2.7/site-packages/pkg_resources.py", line 862, in best_match

    return self.obtain(req, installer) # try and download/install

  File "/usr/local/src/twitter-commons/.python/bootstrap/local/lib/python2.7/site-packages/pkg_resources.py", line 874, in obtain

    return installer(requirement)

  File "/usr/local/src/twitter-commons/.python/bootstrap/local/lib/python2.7/site-packages/setuptools/dist.py", line 339, in fetch_build_egg

    return cmd.easy_install(req)

  File "/usr/local/src/twitter-commons/.python/bootstrap/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 617, in easy_install

    raise DistutilsError(msg)

distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pbr>=1.8')

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /usr/local/src/twitter-commons/.python/bootstrap/build/lockfile
Storing complete log in /tmp/tmpp3r2iO
Downloading/unpacking requests==2.0.0
  Downloading requests-2.0.0.tar.gz (362kB): 362kB downloaded
  Storing download in cache at ./.pants.d/.pip.cache/https%3A%2F%2Fpypi.python.org%2Fpackages%2F8e%2F88%2F102742c48605aef8d39fa719d932c67783d789679628fa1433cb4b2c7a2a%2Frequests-2.0.0.tar.gz
  Running setup.py egg_info for package requests

Installing collected packages: requests
  Running setup.py install for requests

Successfully installed requests
Cleaning up...
Downloading/unpacking setuptools==2.1
  Downloading setuptools-2.1.zip (839kB): 839kB downloaded
  Storing download in cache at ./.pants.d/.pip.cache/https%3A%2F%2Fpypi.python.org%2Fpackages%2F69%2Fbd%2Ff37a4f52937577291f0f18bc51161f3220f2ff815cc976c3f3097bf4a386%2Fsetuptools-2.1.zip
  Running setup.py egg_info for package setuptools

Installing collected packages: setuptools
  Found existing installation: setuptools 0.9.8
    Uninstalling setuptools:
      Successfully uninstalled setuptools
  Running setup.py install for setuptools

    Installing easy_install script to /usr/local/src/twitter-commons/.python/bootstrap/bin
    Installing easy_install-2.7 script to /usr/local/src/twitter-commons/.python/bootstrap/bin
Successfully installed setuptools
Cleaning up...
Traceback (most recent call last):
  File "./src/python/twitter/pants/bin/pants_exe.py", line 30, in <module>
    from twitter.pants.commands import Command
  File "/usr/local/src/twitter-commons/src/python/twitter/pants/commands/__init__.py", line 119, in <module>
    Command._register_modules()
  File "/usr/local/src/twitter-commons/src/python/twitter/pants/commands/__init__.py", line 46, in _register_modules
    __import__(fq_module)
  File "/usr/local/src/twitter-commons/src/python/twitter/pants/commands/goal.py", line 19, in <module>
    import daemon
ImportError: No module named daemon
Unable to build pants!  Cannot continue!

**Comment by stuhood** [comment]
Hm... I don't see a file named `./pants.bootstrap`. Is this an old branch?

On master, should just run `./pants` in the root of the repository.

**Comment by ddwolf** [comment]
I downloaded the sources through this url: https://github.com/twitter/commons/tree/sync-pants-1.2

anyway, I have solved the problem, it's my CA's problem, after Installed the missing CA, the panic dissappeared.
